### ISSUE TITLE
Hummm, intéressant

### ISSUE THREAD

**Issue by quienti** [Lyniven/starlight#1]

**Comment by Lyniven** [comment]
Hey there, please provide description to your issue

**Comment by quienti** [comment]
Tu n'es pas croyable, enfin bon

**Comment by Lyniven** [comment]
Rho j'rigole! 
+ toi aussi le bouton close & comment t'a eue

**Comment by quienti** [comment]
Je trouve ça incroyable, pour quelqu'un qui n'a jamais voulu faire mon idée de projet "Starlight", que 1 an plus tard, par pur hasard, tu te lances à le faire
Je trouve ça très osé

**Comment by Lyniven** [comment]
Je ne le plublirai jamais par respect comme tu l'as dis, c'est ton idée..

Si tu souhaites que cette idée disparaisse, dis le moi, je l'ai relancé dans le seul but de voir les legers progrès que j'ai pu faire, parce que ça reste intéressant, malgré tout je n'ai pas le niveau nécéssaire pour tout faire

**Comment by Lyniven** [comment]
Toi qui a justement dis que tu ne voulais pas dev pendant des mois, je suppose que tu refuserai mon aide si la je la proposait ?

**Comment by quienti** [comment]
Sérieusement ?
Tu penses vraiment que je te donnerai tout mon travail sachant ce que tu as fait ?

**Comment by Lyniven** [comment]
Biensur que non, 
Après tout, j'ai disparu, mais je ne puis revenir étant bloquée ^^"

**Comment by quienti** [comment]
Tu penses que j'ai ma réaction est mal vue ?
Et si tu voulais vraiment revenir, il y a plusieurs façon et faire, et tu le sais

**Comment by Lyniven** [comment]
Non elle est normale. 

Je n'ai pas un million de possibilité, j'étais toujours revenu par le même moyen

**Comment by quienti** [comment]
Tu utilise un faux compte depuis le début, ne me fait pas croire que tu n'es pas capable d'en refaire un
Après tout, tu as toujours inventé une personne à chaque fois

**Comment by Lyniven** [comment]
Ce compte ayant juste changé de nom, ils comptent les plus de 200 000 messages que nous avons eue ensemble, même la première moitié est du bullshit total, mon dernier retour était riche en vérité, j'aurai préféré le garder

**Comment by quienti** [comment]
Tu aurais préféré le garder ?
Pourquoi faire ?

**Comment by Lyniven** [comment]
Je ne sais pas, après tout ce temps, il contient absolument TOUTES nos conversation et échange, je trouve ça nostalgique, pas toi ?

**Comment by quienti** [comment]
Nostalgique ?
Même si effectivement, ça contient tout depuis le début, il contient aussi tous les mensonges, manipulations et autres...

**Comment by Lyniven** [comment]
C'est vrai, mais pas que..

**Comment by quienti** [comment]
Effectivement, pas que...

Tu sais, j'ai fait énormément de chose pour toi, et depuis le début... Il y a beaucoup de chose aujourd'hui, qui sans moi, tu serais en galère et certains choses seraient différentes pour toi...

**Comment by Lyniven** [comment]
Je ne peux pas ignorer le fait que grace à toi, oui ma vie a totalement changé, je te suis infiniment reconaissante pour ton aide, cependant, moi, je ne t'ai servie à rien.

**Comment by quienti** [comment]
Tu as une façon d'être reconnaissante, en disparaissant, pour la xème fois encore...
Pourquoi tu dois servir à quelques choses ? Quand tu offres une amitié et tout les autres choses que l'on a pu faire ou je t'ai fait faire,...

Tu n'as aucun respect de ce que l'on a pu faire depuis tout ce que l'on a vécu, parce que au final, tu finis par disparaître sans aucun mot, ni autre choses...

**Comment by Lyniven** [comment]
Le terme est mauvais oui, je chérie pourtant sincèrement ces moments passés avec toi, mais je finis toujours par disparaître, malheureusement

**Comment by quienti** [comment]
C'est donc qu'en réalité, tu n'as aucune importance en mon égard, puisqu'au final, même si tu dis que tu "chérie" non moment passé, ça n'a aucune importance pour toi

**Comment by Lyniven** [comment]
Je disais justement le contraire, cf google=>chérir

Aussi, il faudrai un autre moyen de communiquer, l'endroit n'est pas le plus approprié je crois

**Comment by quienti** [comment]
Effectivement, l'endroit n'est pas approprié, tu devrais je pense pouvoir supprimer cette "issue"
Et que propose tu comme autre moyen ?

**Comment by Lyniven** [comment]
Le moyen qui t'arrangera, celui utilisé par le passé te dérange-t-il ?

**Comment by quienti** [comment]
Tu as été débloqué à l'instant
